version: "3"
services:
  backend:
    build:
      context: ./backend
      additional_contexts:
        - frontend=./frontend
    environment:
      MODEL: ${MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Change here if you use an external database.
      DATABASE_URL: mysql+pymysql://myuser:mypassword@db/mydb
    ports:
      - "80:8001"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      # You'll want to change these values in production.
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
