version: "3"
services:
  inference:
    build:
      context: ./inference
      dockerfile: Dockerfile.mock
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      INFERENCE_API_URI: http://inference:8000/v1
      MODEL: ${MODEL}
    ports:
      - "8001:8001"
      - "5678:5678"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8001
