name: Lint, Format, and Test Frontend

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - name: Lint
        run: npm run lint
        working-directory: frontend
      - name: Format
        run: npm run format
        working-directory: frontend
      - name: Test
        run: npm test
        working-directory: frontend
